obj-y += basic/lv_theme_basic.o
obj-y += default/lv_theme_default.o
obj-y += mono/lv_theme_mono.o

EXTRA_CFLAGS+=-I$(VPATH)/lib/droidboot/lib/lvgl/src/themes/basic -I$(VPATH)/lib/droidboot/lib/lvgl/src/themes/default -I$(VPATH)/lib/droidboot/lib/lvgl/src/themes/mono
