obj-y += lv_draw.o
obj-y += lv_draw_arc.o
obj-y += lv_draw_img.o
obj-y += lv_draw_label.o
obj-y += lv_draw_layer.o
obj-y += lv_draw_line.o
obj-y += lv_draw_mask.o
obj-y += lv_draw_rect.o
obj-y += lv_draw_transform.o
obj-y += lv_draw_triangle.o
obj-y += lv_img_buf.o
obj-y += lv_img_cache.o
obj-y += lv_img_decoder.o

obj-y += sw/lv_draw_sw.o
obj-y += sw/lv_draw_sw_arc.o
obj-y += sw/lv_draw_sw_blend.o
obj-y += sw/lv_draw_sw_dither.o
obj-y += sw/lv_draw_sw_gradient.o
obj-y += sw/lv_draw_sw_img.o
obj-y += sw/lv_draw_sw_layer.o
obj-y += sw/lv_draw_sw_letter.o
obj-y += sw/lv_draw_sw_line.o
obj-y += sw/lv_draw_sw_rect.o
obj-y += sw/lv_draw_sw_polygon.o
obj-y += sw/lv_draw_sw_transform.o

EXTRA_CFLAGS+="-I$(VPATH)/lib/droidboot/lib/lvgl/draw -I$(VPATH)/lib/droidboot/lib/lvgl/draw/sw"
